apiVersion: v1
kind: PersistentVolume
metadata:
  name: pokemon-pv
  labels:
    topology.kubernetes.io/zone: us-central1-a
    topology.kubernetes.io/region: us-central1
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  gcePersistentDisk:
    pdName: pokemon-disk
    fsType: ext4
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.kubernetes.io/zone
          operator: In
          values:
          - us-central1-a
        - key: kubernetes.io/arch
          operator: In
          values:
          - amd64
